version: '3'

services:
    authors-db-service:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: authors-db-sqlserver
        restart: unless-stopped
        environment: 
        - ACCEPT_EULA=Y
        - MSSQL_PID=Developer
        - SA_PASSWORD=MyStrongPassword@1
        - MSSQL_TCP_PORT=1433
        ports: 
        - "1433:1433"
        networks: 
        - authors-network

networks: 
    authors-network:
        driver: bridge